name: Deploy a app-ordenescompra

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - run: npm ci

      - name: Build (Next.js)
        run: npm run build
        env:
          # NEXT_PUBLIC_* se hornea en tiempo de build -> debe ir acá
          NEXT_PUBLIC_USE_API: "1"

      # Quita las dependencias de desarrollo para aligerar el paquete
      - run: npm prune --omit=dev

      - name: Deploy a Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-ordenescompra
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_DEV }}
          package: .
